### ISSUE TITLE
Add cli option to not run the afterInstall hook

### ISSUE THREAD

**Issue by leabaertschi** [mhassan1/yarn-plugin-after-install#16]
In certain cases I'd like to be able to run `yarn install` without the `afterInstall` hook, the main use case being when it is run in certain build jobs. Is it possible to add something like `--no-afterinstall` to `yarn install`?

**Comment by mhassan1** [comment]
I'd prefer not to add CLI flags, since we would need to add those CLI flags to every `yarn` command that might do an `install`; instead, you could do something like `SKIP_AFTER_INSTALL=true yarn install` and then check for `SKIP_AFTER_INSTALL` inside your script.
